### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by skerit** [pabgn/OpenStar#4]
I can install everything just fine (I even made sure all the versions as they were 3 years ago are installed) but I keep getting this error:

```
[2019-07-03T21:50:11.902Z] [electron-connect] [server] created and listening on 30080
(node) sys is deprecated. Use util instead.
App threw an error when running [ReferenceError: Invalid left-hand side in assignment]
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/skerit/projects/OpenStar/node_modules/webtorrent/index.js:3:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

Seems like an error in the webtorrent module?

**Comment by alexaf2000** [comment]
Yes, there are a lot of dependencies wrong and outdated.

**Comment by pabgn** [comment]
Hello guys,

I will update all this repo with brand new dependencies and fresh code. I’m just curious, what brought you to this project?

**Comment by alexaf2000** [comment]
> Hello guys, I will update all this repo with brand new dependencies and fresh code. I’m just curious, what brought you to this project?
> […](#)
> El 8 febr 2020, a les 10:04, Alex A.F. ***@***.***> va escriure: ﻿ Yes, there are a lot of dependencies wrong and outdated. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

An old post in Ultrastar España. Write me a mail (Is in my profile). Let's talk about it.

**Comment by skerit** [comment]
What, as in "why are you interested in this project"? Having it built using Node of course :)
Ultrastardx is quite difficult to work with because of it being written in Pascal

**Comment by alexaf2000** [comment]
Pascal is difficult and depecrated, the community can do a better and fresh version.

You can look st JustDance Now website as example. Just with your phone and a browser as server everything works very well. Nothing is impossible, so why not try to do a good project based on NodeJS/Electron?

**Comment by pabgn** [comment]
You are all right. True is I’ve got a completely fresh version of this project with an improved pitch analysis + a complete song editor to create new songs using just the web browser. I’ll keep you updated soon

**Comment by basisbit** [comment]
regarding the problem of UltraStar Deluxe being written in objective pascal: there is also the UltraStar Play project, using Unity Engine and C# to target phones/tablets, TVs, game consoles and PC (Windows/Linux/macOS). The basics are already implemented from scratch, but currently the project is missing some people who are good at UI design and also some people to write a webserver for real online multiplayer karaoke. You can find the project at https://github.com/UltraStar-Deluxe/Play

**Comment by alexaf2000** [comment]
Yes, but Unity Engine is too much heavy for this project don't you think? The most important is preserve that little modern platforms as a simple Raspberry Pi can run the software. And using Unity, with a lot of dependencies, problems between versions and publishing... I personally think is not the best solution.

**Comment by basisbit** [comment]
@alexaf2000 because that discussion would be off-topic, I'll keep my reply short and link to https://gitter.im/UltraStar-Deluxe/Play for a chat about this. In short, I disagree with your opinion about Unity. In my experience, it is more lightweight than various JS libs plus a super heavy chromium webbrowser, and Unity is by far much less limiting regarding what you can do for games. Targeting Android on ARMv7 devices which support OpenGL ES and soon Vulcan (on Raspberry Pi 4) can be done.
